# Generated by Django 5.1.5 on 2025-01-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_de_inicio', models.DateField()),
                ('fecha_de_finalizacion', models.DateField()),
                ('estado_actual', models.CharField(choices=[('En progreso', 'En progreso'), ('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20)),
            ],
        ),
    ]
